### ISSUE TITLE
Errors when running harmony

### ISSUE THREAD

**Issue by kaji331** [immunogenomics/harmony#42] opened 2019-08-01 00:42 UTC
I have a 30000 * 110000 dgCMatrix. When I running HarmonyMatrix function, it always throws me an error:

Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
    BLAS/LAPACK routine 'DLASCL' gave error code -4
Calls: HarmonyMatrix -> ncol -> <Anonymous> -> do.call -> <Anonymous>
Execution halted

Even I give HarmonyMatrix a 110000 * 20 pca matrix and do_pca=F, I got the same error.

**Comment by ilyakorsunsky** [comment] 2019-08-05 22:17
@kaji331, thanks for trying out Harmony! 

This error looks similar to one reported on the irlba github: https://github.com/bwlewis/irlba/issues/14

It is very strange that you still get that error when using do_pca=F. Can you reproduce this with a smaller example? It is difficult to debug the problem without more details or a reproducible example.

**Comment by kaji331** [comment] 2019-08-06 00:34
> @kaji331, thanks for trying out Harmony!
> 
> This error looks similar to one reported on the irlba github: [bwlewis/irlba#14](https://github.com/bwlewis/irlba/issues/14)
> 
> It is very strange that you still get that error when using do_pca=F. Can you reproduce this with a smaller example? It is difficult to debug the problem without more details or a reproducible example.

Thank you very much! I finally found that issue on the irlba github. I found that I had some NAs in the sparse matrix, which caused the error. I split a huge sparse matrix to some smaller one and coerced the NA into 0 (because I got another error when I coerce NA into 0 in a huge sparse matrix). Then, I can do HarmonyMatrix function.

**Comment by ilyakorsunsky** [comment] 2019-08-08 23:18
That makes sense, thanks for following up! I will add a check for NA values before I close this issue.

**Comment by wyattmcdonnell** [comment] 2019-09-26 00:01
@kaji331 @ilyakorsunsky FYI we ran into this same issue and traced it back to `irlba` as well since `RunPCA()` wasn't working either. Updating to `Seurat_3.1.0` seemed to address all issues running on GNU/Linux with R 3.6.1, for what it's worth. If you're running R via conda, apparently 3.6.1 through conda/`r-essentials` had some changes to LAPACK/MKL that have caused issues for other people. TL:DR doesn't seem to be `Harmony`'s fault

**Closed** 2020-02-19 16:00 UTC

**Comment by erzakiev** [comment] 2022-10-19 02:56
Same issue here; it turned out to be, indeed, caused by NA values in the data matrix; but the NA values weren't there to begin with; they were, apparently, introduced by the scaling routine scaleData(). This happened because some of the rows in the input matrix were all 0. Would be nice to throw a warning to the user, saying that some rows are all zeroes and it will cause NA values during scaling step
