### ISSUE TITLE
installing harmony

### ISSUE THREAD

**Issue by StanleyYang01** [immunogenomics/harmony#38] opened 2019-06-12 17:40 UTC
Hi, 

I have a problem installing "harmorny". Here is the screenshot of the error. 

![Screenshot 2019-06-12 13 26 33](https://user-images.githubusercontent.com/14856080/59372917-8c0d7580-8d16-11e9-846b-7e0e7b7cd7bf.png)

The R studio pops up the following window.
![Screenshot 2019-06-12 13 21 19](https://user-images.githubusercontent.com/14856080/59373030-c6771280-8d16-11e9-8039-944e6e40ae41.png)

When I hit "Yes", it led me to the following webpage which I still don't know what to do. 
https://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/

Here is my Session info in case you need that. 

Could you please give me some advice to fix the issue? Thank you so much! 

![Screenshot 2019-06-12 13 37 38](https://user-images.githubusercontent.com/14856080/59373411-a005a700-8d17-11e9-85cf-c29c750e4790.png)

**Comment by ilyakorsunsky** [comment] 2019-08-05 22:25
@StanleyYang01, were you able to install command line tools from the link you posted above? The issue seems to be that you don't have the tools to compile the C++ code that comes with Harmony.

**Comment by StanleyYang01** [comment] 2019-08-07 14:08
@ilyakorsunsky , thank you for your reply. I updated my command line tools from the link. But still there are some issues.  I copied the code and the error info below. Any more suggestion for trouble shooting? Thank you! 


> devtools::install_github("immunogenomics/harmony")
Downloading GitHub repo immunogenomics/harmony@master
✔  checking for file ‘/private/var/folders/vs/z75wlg1d603_b5qkzs92mhlng7wwqk/T/Rtmp5aLtGD/remotesbe571f01d4/immunogenomics-harmony-818123e/DESCRIPTION’ ...
─  preparing ‘harmony’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  running ‘cleanup’
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘harmony_0.99.9.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Installing package into ‘/Users/yangs/Library/R/3.6/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘harmony’ ...
** using staged installation
configure: creating ./config.status
config.status: creating src/Makevars
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/yangs/Library/R/3.6/library/Rcpp/include" -I"/Users/yangs/Library/R/3.6/library/RcppArmadillo/include" -I"/Users/yangs/Library/R/3.6/library/RcppProgress/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -DUSE_FLOAT_TYPES=0 -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/yangs/Library/R/3.6/library/Rcpp/include" -I"/Users/yangs/Library/R/3.6/library/RcppArmadillo/include" -I"/Users/yangs/Library/R/3.6/library/RcppProgress/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -DUSE_FLOAT_TYPES=0 -fPIC  -Wall -g -O2  -c harmony.cpp -o harmony.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o harmony.so RcppExports.o harmony.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [harmony.so] Error 1
ERROR: compilation failed for package ‘harmony’
* removing ‘/Users/yangs/Library/R/3.6/library/harmony’
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘/var/folders/vs/z75wlg1d603_b5qkzs92mhlng7wwqk/T//Rtmp5aLtGD/filebe5773b1055b/harmony_0.99.9.tar.gz’ had non-zero exit status

**Comment by ilyakorsunsky** [comment] 2020-02-19 19:52
Thanks @slowkow for pointing out that this installing issue has been previously reported and solved by @aemoor. 

I've now modified the `Makevars.in` file to include the suggested fix. This should make installation on mac and linux systems easier. 

Duplicate of #10

**Closed by ilyakorsunsky** 2020-02-19 19:52 UTC

**Comment by JING202** [comment] 2022-10-05 23:01
Here is the version I used:
ArchR: 1.0.2 
R: 4.2.1
MacOS Big Sur Version 11.7

I did batch correction with "Addharmony". It was showed :

> "Error in .requirePackage("harmony", installInfo = "devtools::install_github(\"immunogenomics/harmony\")") : 
>   Required package : harmony is not installed/found!
>   Package Can Be Installed : devtools::install_github("immunogenomics/harmony")".

Then I tried to install Harmony. But it was failed, as shown below. How can I deal with this issue?

> devtools::install_github("immunogenomics/harmony")
> Downloading GitHub repo immunogenomics/harmony@HEAD
> ✔  checking for file ‘/private/var/folders/wb/j4cm9d3152lfvrf7p91srqrw0000gn/T/RtmpSpaSb9/remotes3235291d09cd/immunogenomics-harmony-6866e01/DESCRIPTION’ ...
> ─  preparing ‘harmony’:
> ✔  checking DESCRIPTION meta-information ...
> ─  cleaning src
> ─  checking for LF line-endings in source and make files and shell scripts
> ─  checking for empty or unneeded directories
> ─  building ‘harmony_0.1.0.tar.gz’
>    
> * installing *source* package ‘harmony’ ...
> ** using staged installation
> ** libs
> clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
> clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c harmony.cpp -o harmony.o
> harmony.cpp:211:52: error: call to 'pow' is ambiguous
>     R.cols(cells_update) = R.cols(cells_update) % (pow((E + 1) / (O + 1), theta) * Phi.cols(cells_update));
>                                                    ^~~
> /Library/Frameworks/R.framework/Versions/4.2/Resources/library/RcppArmadillo/include/armadillo_bits/fn_powext.hpp:33:1: note: candidate function [with T1 = arma::eGlue<arma::eOp<arma::Mat<double>, arma::eop_scalar_plus>, arma::eOp<arma::Mat<double>, arma::eop_scalar_plus>, arma::eglue_div>, T2 = arma::Mat<double>]
> pow
> ^
> ./utils.h:27:9: note: candidate function
> MATTYPE pow(MATTYPE A, const VECTYPE & T) {
>         ^
> 1 error generated.
> make: *** [harmony.o] Error 1
> ERROR: compilation failed for package ‘harmony’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/harmony’
> Warning message:
> In i.p(...) :
>   installation of package ‘/var/folders/wb/j4cm9d3152lfvrf7p91srqrw0000gn/T//RtmpSpaSb9/file3235316e86d1/harmony_0.1.0.tar.gz’ had non-zero exit status

**Comment by JING202** [comment] 2022-10-05 23:15
I just tried install.packages("harmony"), but not "devtools::install_github("immunogenomics/harmony")". It worked. I don't know if the compilation issue. Thanks.
