### ISSUE TITLE
Installation errors (R v4.1.3) 

### ISSUE THREAD

**Issue by ponomarevsy** [immunogenomics/harmony#203] opened 2023-09-15 14:53 UTC
Hello,

We are getting blas and lapack errors, although, both libraries are present inside the conda environment:
```
> library(devtools)
> install_github("immunogenomics/harmony")
...
/path/Anaconda3/2022.05/envs/R-4.1.3/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -llapack
/path/Anaconda3/2022.05/envs/R-4.1.3/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make: *** [/path/Anaconda3/2022.05/envs/R-4.1.3/lib/R/share/make/shlib.mk:10: harmony.so] Error 1
ERROR: compilation failed for package ‘harmony’
* removing ‘/path/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/harmony’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpjOhqX5/file79692d0d5509/harmony_0.1.1.tar.gz’ had non-zero exit status
```

But,
```
(R-4.1.3) [user@node]» conda list blas                                                                                                    
# packages in environment at /path/Anaconda3/2022.05/envs/R-4.1.3:
#
# Name                    Version                   Build  Channel
blas                      2.116                  openblas    conda-forge
blas-devel                3.9.0           16_linux64_openblas    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
openblas                  0.3.21          pthreads_h320a7e8_3    conda-forge
r-rhpcblasctl             0.23_42           r41h57805ef_0    conda-forge

(R-4.1.3) [user@node]» conda list lapack                                                                                                  
# packages in environment at /path/Anaconda3/2022.05/envs/R-4.1.3:
#
# Name                    Version                   Build  Channel
lapack                    3.9.0                    netlib    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
liblapacke                3.9.0           16_linux64_openblas    conda-forge
```

We use RHEL v7.9 "Maipo." Please us know if you have any clues on how to get this fixed. Thank you!

**Comment by pati-ni** [comment] 2023-09-15 15:35
Hi @ponomarevsy,

can you share a `sessionInfo()` of your R?

**Comment by ponomarevsy** [comment] 2023-09-15 16:04
Thank you, @pati-ni. This is what it shows:

```
> sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.9 (Maipo)

Matrix products: default
BLAS/LAPACK: /path/Anaconda3/2022.05/envs/R-4.1.3/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.1.3
>
```

**Comment by ponomarevsy** [comment] 2023-09-15 18:17
Here it goes, @pati-ni:

```
> library(devtools)
Loading required package: usethis
> install_github("immunogenomics/harmony")
Downloading GitHub repo immunogenomics/harmony@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All
 2: CRAN packages only
 3: None
 4: stringi      (1.7.8      -> 1.7.12    ) [CRAN]
 5: cli          (3.6.0      -> 3.6.1     ) [CRAN]
 6: tibble       (3.1.8      -> 3.2.1     ) [CRAN]
 7: pillar       (1.8.1      -> 1.9.0     ) [CRAN]
 8: viridisLite  (0.4.1      -> 0.4.2     ) [CRAN]
 9: labeling     (0.4.2      -> 0.4.3     ) [CRAN]
10: gtable       (0.3.1      -> 0.3.4     ) [CRAN]
11: Rcpp         (1.0.9      -> 1.0.11    ) [CRAN]
12: cpp11        (0.4.3      -> 0.4.6     ) [CRAN]
13: purrr        (1.0.1      -> 1.0.2     ) [CRAN]
14: dplyr        (1.0.10     -> 1.1.3     ) [CRAN]
15: ggplot2      (3.4.0      -> 3.4.3     ) [CRAN]
16: RcppArmad... (0.11.4.2.1 -> 0.12.6.4.0) [CRAN]
17: tidyr        (1.2.1      -> 1.3.0     ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
✔  checking for file ‘/tmp/Rtmp2wu8e7/remotese3244a25d77a/immunogenomics-harmony-63ebd73/DESCRIPTION’ (360ms)
─  preparing ‘harmony’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘harmony_0.1.1.tar.gz’

Installing package into ‘/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘harmony’ ...
** using staged installation
** libs
x86_64-conda-linux-gnu-c++ -std=gnu++11 -I"/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/include" -DNDEBUG  -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/Rcpp/include' -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/RcppArmadillo/include' -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/RcppProgress/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -I/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -Wl,-rpath-link,/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1648493055476/work=/usr/local/src/conda/r-base-4.1.3 -fdebug-prefix-map=/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
x86_64-conda-linux-gnu-c++ -std=gnu++11 -I"/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/include" -DNDEBUG  -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/Rcpp/include' -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/RcppArmadillo/include' -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/RcppProgress/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -I/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -Wl,-rpath-link,/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1648493055476/work=/usr/local/src/conda/r-base-4.1.3 -fdebug-prefix-map=/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3=/usr/local/src/conda-prefix  -c harmony.cpp -o harmony.o
x86_64-conda-linux-gnu-c++ -std=gnu++11 -shared -L/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib -Wl,-rpath-link,/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib -L/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib -o harmony.so RcppExports.o harmony.o -llapack -lblas -lgfortran -lm -lquadmath -L/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/lib -lR
/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -llapack
/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make: *** [/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/share/make/shlib.mk:10: harmony.so] Error 1
ERROR: compilation failed for package ‘harmony’
* removing ‘/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/harmony’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp2wu8e7/filee3242247da8b/harmony_0.1.1.tar.gz’ had non-zero exit status
>
```

**Comment by pati-ni** [comment] 2023-09-15 21:32
Compiler  expects that your R libs should be here:

`/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib`

Your BLAS lives here:

`/path/Anaconda3/2022.05/envs/R-4.1.3/lib/libopenblasp-r0.3.21.so`

Did you move the conda environment manually?

**Comment by ponomarevsy** [comment] 2023-09-18 13:27
That's the same path, @pati-ni, - I've removed the the actual PATH and substituted it with "path" in the second case for shortness.

**Comment by pati-ni** [comment] 2023-09-18 15:00
Ah, okay, that makes sense. Please do not truncate things, as it can get confusing when troubleshooting. Overall, it does not look like something is wrong with harmony. That said, I will try to help you troubleshoot the conda environment.

You need to check two things:

First, make sure your ld path is properly detecting you lib folder which blas lives. conda is using its own ld so you need to find that first.
```bash
## Activate you envirnment
conda activate <your-R-environment>
## This should report an LD variable with a valid binary path
printenv | grep LD
## Print the search path of your environment's LD
$LD --verbose | grep SEARCH_DIR | tr -s ' ;' \\012
```
The `/path/Anaconda3/2022.05/envs/R-4.1.3/lib/` should be included in the last command.

Second, you need to ensure that `libblas.so` and `liblapack.so` symlinks to the `/path/Anaconda3/2022.05/envs/R-4.1.3/lib/libopenblasp-r0.3.21.so`

In my environment it is like this:
```shell
(Renv)  envs/Renv/lib
❯ ls -l libblas* liblapack*
lrwxrwxrwx 1 main main 23 Apr  4 14:39 libblas.so -> libopenblasp-r0.3.21.so
lrwxrwxrwx 1 main main 23 Apr  4 14:39 liblapack.so -> libopenblasp-r0.3.21.so

```

Let me know if any of these were helpful.

**Comment by pati-ni** [comment] 2023-09-18 16:42
Right, I could reproduce the error when I renamed symlink from `libblas.so` to `libblas.so.3`. So creating a copy in your setup should resolve the issue:

What I would suggest is the following:
```bash
cd /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib 
cp libblas.so.3 libblas.so
cp liblapack.so.3 liblapack.so
```

This should fix the environment and you should be able to install harmony. That said, this looks like a conda inconsistency which you may have to refer to the conda upstream maintainers of the R environment and/or BLAS.

**Comment by ponomarevsy** [comment] 2023-09-18 18:44
And that, indeed, solved the problem. Thank you so much, @pati-ni!

```
> library(devtools)
Loading required package: usethis
> install_github("immunogenomics/harmony")
Downloading GitHub repo immunogenomics/harmony@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All
 2: CRAN packages only
 3: None
 4: stringi      (1.7.8      -> 1.7.12    ) [CRAN]
 5: cli          (3.6.0      -> 3.6.1     ) [CRAN]
 6: tibble       (3.1.8      -> 3.2.1     ) [CRAN]
 7: pillar       (1.8.1      -> 1.9.0     ) [CRAN]
 8: viridisLite  (0.4.1      -> 0.4.2     ) [CRAN]
 9: labeling     (0.4.2      -> 0.4.3     ) [CRAN]
10: gtable       (0.3.1      -> 0.3.4     ) [CRAN]
11: Rcpp         (1.0.9      -> 1.0.11    ) [CRAN]
12: cpp11        (0.4.3      -> 0.4.6     ) [CRAN]
13: purrr        (1.0.1      -> 1.0.2     ) [CRAN]
14: dplyr        (1.0.10     -> 1.1.3     ) [CRAN]
15: ggplot2      (3.4.0      -> 3.4.3     ) [CRAN]
16: RcppArmad... (0.11.4.2.1 -> 0.12.6.4.0) [CRAN]
17: tidyr        (1.2.1      -> 1.3.0     ) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
✔  checking for file ‘/tmp/RtmpeKQ5QY/remotes448e9c05eb4/immunogenomics-harmony-63ebd73/DESCRIPTION’ (447ms)
─  preparing ‘harmony’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘harmony_0.1.1.tar.gz’

Installing package into ‘/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘harmony’ ...
** using staged installation
** libs
x86_64-conda-linux-gnu-c++ -std=gnu++11 -I"/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/include" -DNDEBUG  -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/Rcpp/include' -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/RcppArmadillo/include' -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/RcppProgress/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -I/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -Wl,-rpath-link,/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1648493055476/work=/usr/local/src/conda/r-base-4.1.3 -fdebug-prefix-map=/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
x86_64-conda-linux-gnu-c++ -std=gnu++11 -I"/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/include" -DNDEBUG  -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/Rcpp/include' -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/RcppArmadillo/include' -I'/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/RcppProgress/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -I/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -Wl,-rpath-link,/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1648493055476/work=/usr/local/src/conda/r-base-4.1.3 -fdebug-prefix-map=/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3=/usr/local/src/conda-prefix  -c harmony.cpp -o harmony.o
x86_64-conda-linux-gnu-c++ -std=gnu++11 -shared -L/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib -Wl,-rpath-link,/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib -L/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib -o harmony.so RcppExports.o harmony.o -llapack -lblas -lgfortran -lm -lquadmath -L/sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib/R/lib -lR
installing to /sysapps/cluster/software/Anaconda3/2022.05/envs/R-4.1.3/lib64/R/site-library/00LOCK-harmony/00new/harmony/libs
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (harmony)
>
```

**Comment by pati-ni** [comment] 2023-09-18 19:11
Glad to hear it worked; feel free to close the issue!

**Closed** 2023-09-18 19:13 UTC
