### ISSUE TITLE
Cannot install Harmony from GitHub, callr issue

### ISSUE THREAD

**Issue by silvainp** [immunogenomics/harmony#81] opened 2020-03-30 15:25 UTC
Really excited to test Harmony based on the last biorXiv paper but I struggle to install it.

```
Error: Failed to install 'harmony' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/callr/R/callr.rdb' is corrupt
In addition: Warning messages:
1: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
2: In get0(oNam, envir = ns) : internal error -3 in R_decompress1
```

Not sure if it's an issue from my R framework or something from the installing. I delete and re-install callr but same problem.
Thanks for your help.

**Comment by slowkow** [comment] 2020-07-06 13:01
When seeking help with an error, always consider sharing your entire command, the entire output of the command, and also the entire output of `sessionInfo()`.

**Comment by slowkow** [comment] 2020-07-06 14:45
This issue is a duplicate of #87, #88, #90

Could I please ask that we continue this discussion in #90?

**Closed by slowkow** 2020-07-06 14:45 UTC
