### ISSUE TITLE
error during installation harmony in R

### ISSUE THREAD

**Issue by newuser0101** [immunogenomics/harmony#88] opened 2020-05-12 13:00 UTC
Hi,

I tried to install harmony in R (R3.6.3 on Mac), but get an error message in that I cannot resolve.
I first tried it like this:

```
BiocManager::install("harmony")
Warning: package ‘harmony’ is not available (for R version 3.6.3) 
```

Then I tried:

```
install.packages("remotes")
remotes::install_github("immunogenomics/harmony")
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘/var/folders/8z/nknt_n154k54rdwr44sjy3t40000gp/T//Rtmp7jdEzb/filef2f15a26bb8/harmony_1.0.tar.gz’ had non-zero exit status
```

Any ideas on how to fix this? I tried the solution in this thread: Error installing Harmony #10, but am not sure how to make and where to place the makevars file and if this is the solution in my case. Any help would be greatly appreciated!

**Comment by slowkow** [comment] 2020-07-06 13:00
BiocManager is a special package for installing R packages that are hosted on [Bioconductor]. Harmony is not hosted there.

[Bioconductor]: http://bioconductor.org/

When seeking help with an error, always consider sharing your entire command, the entire output of the command, and also the entire output of `sessionInfo()`.

**Comment by slowkow** [comment] 2020-07-06 14:44
This issue is a duplicate of #81, #87, #90

Could I please ask that we continue this discussion in #90?

**Closed by slowkow** 2020-07-06 14:44 UTC
