### ISSUE TITLE
Unable to install from GitHub - error message not informative

### ISSUE THREAD

**Issue by clarsenEmory** [immunogenomics/harmony#87] opened 2020-04-28 16:25 UTC
```
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 13399 Done                    echo 'tools:::.install_packages()'
     13400 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘/var/folders/rl/dx4vfg9n5895b4vlbkxvhpcc0000gp/T//RtmphsJOL4/file332b567aa929/harmony_1.0.tar.gz’ had non-zero exit status
```

**Comment by clarsenEmory** [comment] 2020-04-29 13:27
Now getting this ERROR: installing package indices failed

**Comment by petervangalen** [comment] 2020-05-11 18:53
I'm having a similar issue. On R version 3.6.1 it works fine, but with R version 4.0.0 the following happens:

> install_github("immunogenomics/harmony")
Downloading GitHub repo immunogenomics/harmony@master
   checking for file ‘/private/var/folders/lm/5fkddq9119v31_40dqj5pf2m0000gn/T/RtmpxopenE/remotes13697ed99c5b/immunoge✔  checking for file ‘/private/var/folders/lm/5fkddq9119v31_40dqj5pf2m0000gn/T/RtmpxopenE/remotes13697ed99c5b/immunogenomics-harmony-88b1e2a/DESCRIPTION’
─  preparing ‘harmony’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘harmony_1.0.tar.gz’

* installing *source* package ‘harmony’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c harmony.cpp -o harmony.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o harmony.so RcppExports.o harmony.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-harmony/00new/harmony/libs
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
sh: line 1:  5039 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/lm/5fkddq9119v31_40dqj5pf2m0000gn/T//RtmpbvCZdk/file13943a8c2b58'
ERROR: installing package indices failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/harmony’
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘/var/folders/lm/5fkddq9119v31_40dqj5pf2m0000gn/T//RtmpxopenE/file136923100a50/harmony_1.0.tar.gz’ had non-zero exit status

**Comment by newuser0101** [comment] 2020-05-13 10:20
I have the exact same issue with R 3.6.3:
Error: ‘/var/folders/8z/nknt_n154k54rdwr44sjy3t40000gp/T//Rtmp7jdEzb/filef2f15a26bb8/harmony_1.0.tar.gz’ had non-zero exit status

**Comment by 13mhzeng** [comment] 2020-05-21 01:54
I have the same issue too with R3.6.3, is there any ways to solve this problam?
thx!

**Comment by ilonliu** [comment] 2020-05-25 00:41
Same as described above: no problems on R version 3.6.2, however getting the same installation error after updating to R version 4.0.0:

Downloading GitHub repo immunogenomics/harmony@master
✓  checking for file ‘/private/var/folders/gw/fht9stfj07xgnyfjcd5lj3g1zjt397/T/RtmpJGuwCj/remotes4a1b407eafa3/immunogenomics-harmony-88b1e2a/DESCRIPTION’ ...
─  preparing ‘harmony’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘harmony_1.0.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
* installing *source* package ‘harmony’ ...
** using staged installation
** libs
/usr/local/clang4/bin/clang++ -fopenmp -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
/usr/local/clang4/bin/clang++ -fopenmp -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c harmony.cpp -o harmony.o
/usr/local/clang4/bin/clang++ -fopenmp -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/clang4/lib -o harmony.so RcppExports.o harmony.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-harmony/00new/harmony/libs
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
sh: line 1: 65410 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/gw/fht9stfj07xgnyfjcd5lj3g1zjt397/T//Rtmp77818T/fileff69679f63ea'
ERROR: installing package indices failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/harmony’
installation of package ‘/var/folders/gw/fht9stfj07xgnyfjcd5lj3g1zjt397/T//RtmpJGuwCj/file4a1b27a4f51c/harmony_1.0.tar.gz’ had non-zero exit status

Any help is much appreciated, thanks!!

**Comment by RMolania** [comment] 2020-05-27 03:51
I have the same issue!!

**Comment by LW-Krugie** [comment] 2020-05-27 05:25
Same issue here: 

`> install_github("immunogenomics/harmony")
Downloading GitHub repo immunogenomics/harmony@master
✓  checking for file ‘/private/var/folders/bd/z0rpv5y16kg063nbdktw1vqm0000gn/T/RtmppKAjZP/remotesafab7f6d75a5/immunogenomics-harmony-88b1e2a/DESCRIPTION’ ...
─  preparing ‘harmony’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘harmony_1.0.tar.gz’
   
* installing *source* package ‘harmony’ ...
** using staged installation
** libs
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/RcppProgress/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c harmony.cpp -o harmony.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o harmony.so RcppExports.o harmony.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-harmony/00new/harmony/libs
** R
** data
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
sh: line 1: 45057 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/bd/z0rpv5y16kg063nbdktw1vqm0000gn/T//RtmpPysnzR/fileafe67961bd08'
ERROR: installing package indices failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/harmony’
Error: Failed to install 'harmony' from GitHub:
  (converted from warning) installation of package ‘/var/folders/bd/z0rpv5y16kg063nbdktw1vqm0000gn/T//RtmppKAjZP/fileafab680f87aa/harmony_1.0.tar.gz’ had non-zero exit status
> `

**Comment by slowkow** [comment] 2020-07-05 20:28
Could I please ask if using R 4.0.2 still results in this error? I wasn't able to reproduce the error on Linux here: https://github.com/immunogenomics/harmony/issues/90#issuecomment-653934908

**Comment by slowkow** [comment] 2020-07-05 22:53
I used Travis to test macOS and Linux with R 3.6.3, R 4.0.2, and the latest development version of R. All six of the tests passed without installation issues.

Test results can be viewed here: https://travis-ci.org/github/slowkow/harmony/builds/705198401

For those of you experiencing issues, I'm sorry for the trouble, but it seems that I am not able to reproduce the problem. You might consider trying the installation again with a fresh R session. Also consider restarting your computer before trying again. Let us know if you think there are additional details about your system that might be relevant to this issue.

In the error message shared by @LW-Krugie we can see this:

```
sh: line 1: 45057 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/bd/z0rpv5y16kg063nbdktw1vqm0000gn/T//RtmpPysnzR/fileafe67961bd08'
ERROR: installing package indices failed
```

My interpretation of this is that your system is using `sh` to run `R` to run a script in the file

```
/var/folders/bd/z0rpv5y16kg063nbdktw1vqm0000gn/T//RtmpPysnzR/fileafe67961bd08
```

This process is being killed with [signal 9 (SIGKILL)](https://unix.stackexchange.com/questions/281439/why-should-i-not-use-kill-9-sigkill). I don't know why the process is being terminated. Maybe there's a clue in the R script inside the file `fileafe67961bd08`?

Any ideas are welcome. Good luck! If you find that your issue is resolved, please do let us know!

**Comment by slowkow** [comment] 2020-07-06 14:39
@clarsenEmory 
@petervangalen
@newuser0101
@13mhzeng
@ilonliu
@RMolania
@ankushs0128

Please consider sharing more information.

By sharing the complete output for the `sessionInfo()` command in R, we will learn:

- What operating system are you using? macOS, Windows, Linux, etc.
- What R version are you using? 3.6.2, 4.0.0, etc.

Please also share:

- How did you install R? Homebrew? The .pkg file from r-project.org? Something else?

Here is the information I have gleaned from messages so far:

![image](https://user-images.githubusercontent.com/209714/86605643-f540d600-bf74-11ea-849a-f1a6f6252914.png)

**Comment by slowkow** [comment] 2020-07-06 14:45
This issue is a duplicate of #81, #88, #90

Could I please ask that we continue this discussion in #90?

**Closed by slowkow** 2020-07-06 14:45 UTC
